### ISSUE TITLE
config name

### ISSUE THREAD

**Issue by skaviouz** [squeek502/AppleCore#10]
Sorry for the dumbest issue ever, but I was helping someone earlier and noticed this typo
##### B:show.food.exhaustion.hud.overlay=
should say
##### B:show.food.exhaustion.hud.underlay=
as it's an underlay and not an overlay

Sorry if it's nitpicky, but just means you don't have any other errors/issues and that is good :laughing:

**Comment by squeek502** [comment]
:smile:
