### ISSUE TITLE
Crash on 1.12.2

### ISSUE THREAD

**Issue by maginator** [squeek502/AppleCore#100]
Hi.
My Game crash on Loading a World tgis is the Crash Repo:

https://gist.github.com/maginator/c30c78dffb265d0c197505378f32621b

Forge: 1.12.2-14.23.0.2517
Apple Core: 2.2.2

**Comment by squeek502** [comment]
You must use AppleCore for 1.12.2, specifically (`AppleCore-mc1.12.2-2.2.2.jar`). You're currently using the one for 1.12.1 (`AppleCore-mc1.12.1-2.2.2.jar`).
