### ISSUE TITLE
[1.12.2] No Hunger bars shown?!

### ISSUE THREAD

**Issue by Marcel40625** [squeek502/AppleCore#101]
Hey, i installed this coremod to have hungerbars in tooltips. but i see nothing.

am i doing something wrong?

**Comment by squeek502** [comment]
You probably figured it out, but for future reference, that part of the mod got moved to [AppleSkin](https://minecraft.curseforge.com/projects/appleskin)

**Comment by Marcel40625** [comment]
yeah i have seen it, testing it atm and would have posted it :) ... sorry but a bit confusing
