### ISSUE TITLE
Incorrect AppleCore tooltips with BetterWithMods

### ISSUE THREAD

**Issue by adegarimore** [squeek502/AppleCore#102]
https://github.com/BetterWithMods/BetterWithMods/issues/627

**Comment by squeek502** [comment]
Need more info (mod versions, MC version, etc). This should have been solved by https://github.com/squeek502/AppleSkin/issues/9 a while ago.

**Comment by adegarimore** [comment]
Minecraft 1.12.2
Forge 2517
AppleCore 1.12.2-2.2.2

Modlist
![screenshot from 2017-11-02 13-41-21](https://user-images.githubusercontent.com/7571304/32349282-b8cd1e34-bfd3-11e7-8cf3-5fa66cd12391.png)

**Comment by squeek502** [comment]
I think the scale factor I used was wrong the whole time. Will implement a better solution in a bit, thanks for reporting it.

**Comment by squeek502** [comment]
Should be fixed in AppleSkin v1.0.9:
https://github.com/squeek502/AppleSkin/releases/tag/v1.0.9
https://minecraft.curseforge.com/projects/appleskin/files (once it's approved)
