### ISSUE TITLE
Help Me:

### ISSUE THREAD

**Issue by lilgandhi1199** [squeek502/AppleCore#103]

**Comment by lilgandhi1199** [comment]
I've found the IAppleCoreAccessor, IAppleCoreMutator, and AppleCoreAccessorMutatorImpl then imported all three into my class but I don't understand how I can use the functions defined there? I type them in and it doesn't offer to resolve them or change parameters... it just wants me to make the methods!

**Comment by squeek502** [comment]
You only need the files in the `squeek.applecore.api` package. To get instances of `IAppleCoreAccessor`, etc, use the fields in [`squeek.applecore.api.AppleCoreAPI`](https://github.com/squeek502/AppleCore/blob/1.12.2/java/squeek/applecore/api/AppleCoreAPI.java).

- An example of this sort of thing can be found [on the wiki](https://github.com/squeek502/AppleCore/wiki/Using-the-AppleCore-API) and [in the example mod](https://github.com/squeek502/AppleCore/blob/1.10.2/java/squeek/applecore/example/FoodValuesTooltipHandler.java)
- A really simple and complete mod that uses AppleCore can be found here: https://github.com/squeek502/HungerInPeace
- The most preferred method for getting the AppleCore API in your dev environment is by [including the maven repository in your build.gradle](https://github.com/squeek502/AppleCore/wiki/Building-against-AppleCore)

**Comment by lilgandhi1199** [comment]
Thank You!
