### ISSUE TITLE
Another Question:

### ISSUE THREAD

**Issue by lilgandhi1199** [squeek502/AppleCore#104]
I see you can set the current hunger and saturation but is it possible to simply grab the current hunger and saturation?

**Comment by lilgandhi1199** [comment]
I would appreciate your help because right now I am trying to track Exhaustion/Food/Death events because I see this as the only way to know the current hunger and saturation

**Comment by squeek502** [comment]
That's possible with just vanilla Minecraft:
`player.getFoodStats().getFoodLevel()`
`player.getFoodStats().getSaturationLevel()`
