### ISSUE TITLE
1.12.2 crash

### ISSUE THREAD

**Issue by WithoutHope** [squeek502/AppleCore#105]
I was trying to play some minecraft. I've downloaded lastest version of mod, core and forge. Here is my crash report. Good luck..
[crash-2017-11-18_21.40.50-client.txt](https://github.com/squeek502/AppleCore/files/1485008/crash-2017-11-18_21.40.50-client.txt)

**Comment by squeek502** [comment]
On first glance, it doesn't seem related to AppleCore. This crash doesn't happen if you remove AppleCore?

**Comment by WithoutHope** [comment]
I tried it just now and yes it does crush without AppleCore. I gues i need
to go back to minecraft 1.10 :/ Thanks for your time.

2017-11-19 2:57 GMT+01:00 Ryan Liptak <notifications@github.com>:
