### ISSUE TITLE
Resource pack integration

### ISSUE THREAD

**Issue by DaOrkMasta** [squeek502/AppleCore#11]
I would like to integrate an upscaled resource pack into the mod pack that I am creating.

I have edited the default icons.png (in your .jar) to be upscaled and outline the new hunger icon in the resource pack.

The tooltip icons are correctly shown, but when holding a food item, the HUD overlay does not appear and neither does the current saturation level.

The grey progress bar (from AppleCore) behind the hunger bar is shown correctly.

**Comment by squeek502** [comment]
What does your AppleCore.cfg look like?

**Comment by DaOrkMasta** [comment]
I have not changed the config file:

<code>client {
    B:show.food.exhaustion.hud.overlay=true

    B:show.food.stats.in.debug.overlay=true

    B:show.food.values.hud.overlay=true

    B:show.food.values.in.tooltip=true

    B:show.saturation.hud.overlay=true
}</code>

**Comment by squeek502** [comment]
Mind uploading the resource pack (or just your modified icons.png)?

**Comment by DaOrkMasta** [comment]
![icons](https://cloud.githubusercontent.com/assets/7267531/5849453/dab538c4-a1b3-11e4-9a94-ed3b3f8f289b.png)
![icons](https://cloud.githubusercontent.com/assets/7267531/5849459/f0d784c2-a1b3-11e4-86b7-26745f826a01.png)

**Comment by squeek502** [comment]
Seems to work fine for me:

![2015-01-21_18 33 36_cr](https://cloud.githubusercontent.com/assets/2389051/5849574/320c5dfe-a19c-11e4-9f2d-b2b5aac42639.png)

Perhaps another mod is interfering with the [RenderGameOverlayEvent.ElementType.FOOD RenderGameOverlayEvent.Post](https://github.com/squeek502/AppleCore/blob/master/java/squeek/applecore/client/HUDOverlayHandler.java#L66) where AppleCore's hunger overlays get drawn?

Does the overlay work for you without the resource pack enabled? What other mods do you have installed?

**Comment by DaOrkMasta** [comment]
After further testing, are removal of several mods, I have found the issue. "Duel Hotbars" shifts the default position of the hunger bar and therefore the hunger overlay would need to be moved as well. BUT, if the grey checker pattern still shows behind the hunger bar with "Duel Hotbars" installed, then why doesn't the overlay?

**Comment by squeek502** [comment]
That is an ancient Dual Hotbars bug that the author fixed and then accidentally unfixed. Not sure why it hasn't been re-fixed.

See:
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2178797-dual-hotbars?comment=29 and http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2222837-applecore-an-api-for-modifying-the-food-and-hunger?comment=52
