### ISSUE TITLE
Instant crash with twitch launcher, unable to get crash log

### ISSUE THREAD

**Issue by usafphoenix** [squeek502/AppleCore#110]
Building a pack, but for some reason as soon as i add applecore (required for both spice of life and hunger overhaul), the pack won't even load past the initial stage of loading up mods. doesn't even give me a proper crash report. 
What methods can i take to isolate or locate the cause and help find a fix?

**Comment by usafphoenix** [comment]
i'll keep working on it and try and continue removing/halving the mods installed concurrently with applecore to try and see what triggers this odd crash (usually when building a pack i get dependency crashes first, then deal with any block/potion/biome ID collisions after that, and then I'm usually able to go about making config changes or recipe scripts, so i think this may be the first time i've gotten an actual "crash" without it pooping out a crash report in the mod folder.) so that's kinda odd.

**Comment by usafphoenix** [comment]
this is what i got;

Unable to launch java.lang.reflect.InvocationTargetException 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	at java.lang.reflect.Method.invoke(Method.java:483) 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) Caused by: java.lang.NoClassDefFoundError: net/minecraft/entity/player/EntityPlayer 	at net.minecraft.client.main.Main.main(SourceFile:72) 	... 6 more Caused by: java.lang.ClassNotFoundException: net.minecraft.entity.player.EntityPlayer 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) 	... 7 more Caused by: java.lang.RuntimeException: EntityPlayer.getItemInUseDuration: no replacements made 	at squeek.applecore.asm.module.ModuleFoodEatingSpeed.patchGetItemInUseDuration(ModuleFoodEatingSpeed.java:110) 	at squeek.applecore.asm.module.ModuleFoodEatingSpeed.transform(ModuleFoodEatingSpeed.java:50) 	at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:41) 	at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) 	... 9 more
--
18:53:38 | game |   | error | Exception in thread "main"   <log4j:Event logger="STDERR" timestamp="1514616818265" level="INFO" thread="main">     <log4j:Message><![CDATA[[java.lang.Throwable$WrappedPrintStream:println:748]: cpw.mods.fml.relauncher.FMLSecurityManager$ExitTrappedException]]></log4j:Message>   </log4j:Event>
18:53:38 | monitor | Process Monitor | error | expected <

**Comment by squeek502** [comment]
Most likely a conflict with another core mod you have installed. Could you provide a mod list and what Minecraft/Forge version you are running?

**Comment by usafphoenix** [comment]
I backed up the config folder, deleted the instance, and rebuilt the pack from scratch with a fresh install of minecraft and forge, then added a few mods at a time till all the original mods were all running concurrently. And the crash didn't happen again, so either a problem with minecraft/forge install, or i had a corrupted jar file somehow [a mod that maybe didn't fully-download properly?], or something else entirely. But its fine now i suppose

**Comment by squeek502** [comment]
Strange!
