### ISSUE TITLE
FoodStats.addStats does not get saturation from the FoodValues getters

### ISSUE THREAD

**Issue by primetoxinz** [squeek502/AppleCore#121]
I was attempting to override how saturation values are retrieved for a HCHunger bug and noticed that at [this](https://github.com/squeek502/AppleCore/blob/1.12.2/java/squeek/applecore/asm/reference/FoodStatsModifications.java#L35) line, the additional saturation value is calculated from the FoodValues field rather than the `getSaturationIncrement` method.

**Comment by squeek502** [comment]
By the time the `int, float` version of `addStats` is called, we no longer have a reference to the FoodValues instance, so there's not really a `getSaturationIncrement` function that can be called (except on a new instance of FoodValues, but that'd bypass any customization unless I'm thinking about this wrong).

I see two possibilities:
- What is currently possible is listening for `FoodEvent.FoodStatsAddition`, canceling it, and then modifying the `FoodStats` fields yourself (essentially reimplement/override `FoodStats.addStats`)
- I could add a new event specifically for this purpose, but given the above *should* work that might not be necessary.

Untested example code:
```java
@SubscribeEvent
public void onFoodStatsAddition(FoodEvent.FoodStatsAddition event)
{
	// cancel the default
	event.setCanceled(true);

	int maxHunger = AppleCoreAPI.accessor.getMaxHunger(event.player);
	int newHunger = Math.min(event.player.getFoodStats().getFoodLevel() + event.foodValuesToBeAdded.hunger, maxHunger);
	event.player.getFoodStats().setFoodLevel(newHunger);

	float saturationIncrement = event.foodValuesToBeAdded.hunger * event.foodValuesToBeAdded.saturationModifier * 2f;
	float newSaturation = Math.min(event.player.getFoodStats().getSaturationLevel() + saturationIncrement, newHunger);
	AppleCoreAPI.mutator.setSaturation(event.player, newSaturation);
}
```

**Comment by primetoxinz** [comment]
Yeah, you're right. I overlooked that this was the int,float version. Thought it was still the itemstack one, my bad.
The event will do. 
Thanks :)
