### ISSUE TITLE
Crash on world load after update from 3.1.1 to 3.1.2

### ISSUE THREAD

**Issue by d3radicated** [squeek502/AppleCore#125]
As the title says. I don't know what mod conflicts with the new version. Here's the [crash log](https://pastebin.com/sRxs0FGr).

**Comment by DWX12** [comment]
First one that I see is Spice of Life Carrot, seems like that's one of the mods affected by the new Applecore. After that, I'd look at everything that adds food, mainly mods that focus on food or have alot in the mod.

**Comment by squeek502** [comment]
Sorry, I'm a doofus, this happens with just AppleCore alone. Don't use 3.1.2. Will release a fix in a bit.

**Comment by squeek502** [comment]
Fixed in 3.1.3 once it gets approved: https://minecraft.curseforge.com/projects/applecore/files
