### ISSUE TITLE
[1.12.2] Crash on world creation with Galacticraftcore 4.0.1.177 and Applecore 3.1.2

### ISSUE THREAD

**Issue by DWX12** [squeek502/AppleCore#126]
Seems that Galacticraftcore is incompatible with Applecore now.
Same crash report in two convenient forms.

https://hastebin.com/acinisoxax.sql

[crash-2018-06-12_01.24.45-server.txt](https://github.com/squeek502/AppleCore/files/2093221/crash-2018-06-12_01.24.45-server.txt)

**Comment by d3radicated** [comment]
Similar to issue #125.

**Comment by squeek502** [comment]
Sorry, I'm a doofus, this happens with just AppleCore alone. Don't use 3.1.2. Will release a fix in a bit.

**Comment by squeek502** [comment]
Fixed in 3.1.3 once it gets approved: https://minecraft.curseforge.com/projects/applecore/files
