### ISSUE TITLE
Inquiring on the potential of a 1.13+ update.

### ISSUE THREAD

**Issue by primetoxinz** [squeek502/AppleCore#140]
Hey squeek,

I just wanted to ask if you have plans to port AppleCore to 1.13, or are potentially waiting for 1.14.
Of course there is no rush on it, I just wanted to know.
If not I may take it up myself for continuing to use it with Better With Mods.

Thanks for all your work!

**Comment by squeek502** [comment]
Definitely plan to port to 1.13, but not sure exactly when I'll get to it.

**Comment by primetoxinz** [comment]
Ok, thanks for the quick response
