### ISSUE TITLE
crashing

### ISSUE THREAD

**Issue by aetreia** [squeek502/AppleCore#141]
I made my own modpack and Vanillafix tells me your mod could be the reason my game crashes.
i am adding bugreport.

https://paste.dimdev.org/oneruqazaw.mccrash

**Comment by squeek502** [comment]
Looks to me like a crash caused by PlusTiC expecting something from Cosntruct's Armory to exist. Not related to AppleCore.

**Comment by squeek502** [comment]
Relevant PlusTiC issue: https://github.com/Landmaster/PlusTiC/issues/250

Updating your PlusTiC should fix it.
