### ISSUE TITLE
How do I return the Vanilla foods back to it's original settings?

### ISSUE THREAD

**Issue by RepoDraghon** [squeek502/AppleCore#144]
1.12.2 
I want to play this game with a mod that requires this one but I want to play with the stock values...

**Comment by squeek502** [comment]
This mod on its own does not change food values at all. You'd need to look at how to configure whatever mod is using AppleCore to alter the food values.

**Comment by RepoDraghon** [comment]
Which mod in MC.Eternal Mod Pack is editing it? I see one potential but I do not see a config file...

**Comment by squeek502** [comment]
Don't know, you'd have to ask the mod pack maker.
