### ISSUE TITLE
/hunger command requires permission level 4 and is not allowed in command blocks.

### ISSUE THREAD

**Issue by James103** [squeek502/AppleCore#150]
As shown in the following code, the `/hunger` command requires permission level 4, rendering it unable to be used in command blocks. Many other commands that strictly only modify player and world data (like `/xp`, `/reload`, `/summon`, `/data`) only require permission level 2 and are able to be used in command blocks. Why is that the case and can the `/hunger` command be changed to require permission level 2 and work in command blocks like other similar commands?

https://github.com/squeek502/AppleCore/blob/e615a2d288fdc853d83770d4b1855234fdf51c91/java/squeek/applecore/commands/CommandHunger.java#L33-L36

**Comment by squeek502** [comment]
Was probably copied from somewhere without realizing what it meant. Will happily accept a PR that fixes this.
