### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by epicwappy20** [squeek502/AppleCore#153]
i am using applecore and appleskin plus a few other mods and I get this error when I load up a world. The game crashed whilst ticking player
Error: java.lang.ClassCastException: net.minecraft.util.FoodStats cannot be cast to squeek.applecore.asm.util.IAppleCoreFoodStats

I am using mc 1.10.2

**Comment by squeek502** [comment]
Likely means that another mod you have is overriding FoodStats which is incompatible with AppleCore. Would need your full mod list.

**Comment by epicwappy20** [comment]
mod list: applecore, apppleskin, youtubers+, cyclic, neat, and waila(mod page and file are called hwyla)

**Comment by squeek502** [comment]
My guess would be Youtubers+, the others should be fine I believe. If you can, try removing Youtubers+ and see if the crash goes away.

**Comment by epicwappy20** [comment]
didn't work when i removed youtubers +

**Comment by squeek502** [comment]
Does it work if you remove all other mods except AppleCore?

By the way, with your mod list, AppleCore doesn't seem to be doing anything, so you could just remove AppleCore if you want. Is there any particular reason you have it installed?

**Comment by epicwappy20** [comment]
I wanted to use appleskin to get a better GUI for food. also I was planning on adding more mods because I was going to do a modded survival.

**Comment by squeek502** [comment]
AppleSkin is useable without AppleCore. AppleCore is only needed for mods like The Spice of Life, Hunger Overhaul, etc.
