### ISSUE TITLE
Crash with ForgeEssientals

### ISSUE THREAD

**Issue by ultrasn0w** [squeek502/AppleCore#17]
Hey AppleCore dev,
Tried to run a Server with ForgeEssientals, however the server crashes soon after starting.
Crash Report:
http://pastebin.com/0RF45LYT
Issue at FEGit:
https://github.com/ForgeEssentials/ForgeEssentialsMain/issues/1372

Greetings
ultrasn0w

**Comment by ultrasn0w** [comment]
Confirmed that this is FastCraft/AppleCore related, #18 &  #19 are more correct. This Issue may be closed since ForgeEssentials has nothing to do with this.

**Comment by squeek502** [comment]
Thanks for the confirmation
