### ISSUE TITLE
Updated applecore to 1.2.1 in modpack and it broke

### ISSUE THREAD

**Issue by Xiaminou** [squeek502/AppleCore#22]
I updated applecore to 1.2.1 in my modpack and it resulted in a crash, so I rolled back and still crashed, I tried removing the config files and still crashed. I finally had to disable the mod entirely.

first crash report : http://pastebin.com/DxhLZhSU
last crash report : http://pastebin.com/C5tuHpah

**Comment by squeek502** [comment]
Where did you download 1.2.1? That version was revoked because it is known to be broken and is not ready yet. See #16.

Use 1.1.0 instead.

**Comment by Xiaminou** [comment]
Curseforge, oh okay I rolled back to to 1.2.0 I thought it was the version I used before, my bad.

**Comment by squeek502** [comment]
1.2.0 and 1.2.1 shouldn't exist on CurseForge.

Do you see them here?

http://minecraft.curseforge.com/mc-mods/224472-applecore/files

**Comment by Xiaminou** [comment]
no, but I still see them on the Curse Launcher

**Comment by squeek502** [comment]
Seems to be a known issue with the latest update to the curse launcher. Thanks for letting me know.

> [13:32] <squeek> files deleted from curseforge still show up in the curse launcher
[13:32] <jadedcat> no that's new
[13:32] <jadedcat> someone made a booboo
[13:32] <squeek> ok
[13:32] <squeek> applecore 1.2.0 and 1.2.1 were deleted months ago but still show up in the launcher
[13:32] <jadedcat> I just screamed bloody murder this morning
[13:33] <squeek> :)
[13:33] <jadedcat> it happened with the last update
