### ISSUE TITLE
server crash when harvestcraft saplings grow

### ISSUE THREAD

**Issue by josef-spak** [squeek502/AppleCore#29]
After adding AppleCore to my smallish modpack I was getting crashes when a harvestcraft apple sapling attempted to grow in world tick. I thought it was a HarvestCraft issue but then I looked at the trace when bonemealing the sapling. Is this something that can be fixed in AppleCore?

[crash-2015-07-17_22.58.31-server.txt | uploaded via ZenHub](https://files.zenhub.io/55a9712d466fe68f139b960c)

**Comment by squeek502** [comment]
Use AppleCore 1.1.0. The latest dev builds are not stable.

Keeping this open, though, as it still needs to be fixed before the new version can be released.
