### ISSUE TITLE
DualHotBar and the Applecore Overlay

### ISSUE THREAD

**Issue by utoc** [squeek502/AppleCore#30]
Hello!  I have a very minor issue with DualHotBar in conjuction with AppleCore.  When using DualHotBar and having selected a food item, AppleCore shows the food value and saturation under the upper hotbar. If you're unable to move the saturation/food value automatically to overlay on top of the existing hunger bar, a manual config option would be just fine.

Here is a picture in case my words have failed to describe the issue: http://i.imgur.com/66mLGYl.png

Love your mods, thanks for being awesome!

**Comment by squeek502** [comment]
See [this post](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2222837-applecore-an-api-for-modifying-the-food-and-hunger?comment=52):

> This can and should be fixed on Dual Hotbar's end and it was fixed in a previous version but seems to have been reverted by accident or something (also, the fix is in the 1.6.4 version). His `shiftRendererDown` method in `RenderHandler` needs to have `@SubscribeEvent(priority=EventPriority.LOWEST)` instead of `@SubscribeEvent(priority=EventPriority.HIGHEST)`.

Unfortunately @RebelKeithy seems to have stopped updating Dual Hotbars.

**Comment by utoc** [comment]
Thanks for linking that, S/he has their code on github so I'll try to fork the code and make a build that works.

**Comment by squeek502** [comment]
Ah, didn't realize it got put on Github. I'll make a pull request as well.

**Comment by squeek502** [comment]
Submitted a pull request. If you want it early, you can clone this: https://github.com/squeek502/DualHotbar/tree/patch-1

and run `gradlew build` in the cloned directory.

**Comment by utoc** [comment]
Got it, thank you again!

**Comment by brandyyn** [comment]
Hey, Im sorry to revive a dead thread but how do I install this patch?

**Comment by squeek502** [comment]
@sonicbrandyn here's a build that should work: [dualhotbar-1.7.10-1.6.1.jar](https://www.ryanliptak.com/misc/dualhotbar-1.7.10-1.6.1.jar)

**Comment by brandyyn** [comment]
Do I just put it in the mods folder? And does it work with the botania mana bar too?
