### ISSUE TITLE
No 1.2.x release?

### ISSUE THREAD

**Issue by IceDragon200** [squeek502/AppleCore#31]
The AppleCore topic on minecraftforums says cleary "v1.2.1 (for Minecraft 1.7.10):", curseforge still has only `1.0.x`, and `1.1.x`, no `1.2.x`, unless I'm looking in the wrong place.

If I'm doing something wrong, please direct me.

 I'm reaching out due to the following issues experienced by @PitchBright
https://github.com/alatyami/Growthcraft-1.7/pull/27

**Comment by squeek502** [comment]
Ah, sorry, there are outstanding issues with 1.2.x, so I revoked that version until they are fixed (which is taking a long time, unfortunately). See #27, #18, #19.

I thought I fixed the thread a long time ago, but must have accidentally reverted it. Will fix it again, thanks for the heads up.

Keeping this open until 1.2.x is released.

**Comment by squeek502** [comment]
Closing; released as 1.3.0: https://github.com/squeek502/AppleCore/releases
