### ISSUE TITLE
Incompatible with KCauldron

### ISSUE THREAD

**Issue by squeek502** [squeek502/AppleCore#46]
See squeek502/SpiceOfLife#80

Not sure what to do about this.

**Comment by johnfg2610** [comment]
maybe go speak with kcaudron staff see if they will fix it

**Comment by squeek502** [comment]
It would make more sense to fix it on AppleCore's side. It's not a problem with KCauldron, it's an incompatibility.

**Comment by johnfg2610** [comment]
ye true

**Comment by johnfg2610** [comment]
i have done some testing and it appears to be a new issue as we are now running version 1.10 and it fixes the issue

**Comment by squeek502** [comment]
Interesting, thanks for the info.

**Comment by johnfg2610** [comment]
im not a java dev but it only happens on one plant that is fluffy plant from silent gems 
i also was looking at what changed between versions and seen 
https://github.com/squeek502/AppleCore/commit/6468455ae2dd04a24ec89125d2b6ec94d8eaf500
https://github.com/squeek502/AppleCore/commit/6468455ae2dd04a24ec89125d2b6ec94d8eaf500
maybe they have something to do with it :) but idk
