### ISSUE TITLE
[1.7.10] server crash

### ISSUE THREAD

**Issue by johnfg2610** [squeek502/AppleCore#49]
http://pastebin.com/5eqjdkcH

**Comment by squeek502** [comment]
Same type of crash as #48, but on `BlockCrops`. Maybe a KCauldron incompatibility.

**Comment by johnfg2610** [comment]
possible it is used on a large KCauldron server would this be fixable ?

**Comment by squeek502** [comment]
It's fixable, but I'm not sure when (or if) it'll get fixed. There are other known incompatibilities with KCauldron, see #46.

**Comment by squeek502** [comment]
Might have been fixed by f62ad21575bb1c53908d389a07c7a58e735425d1. Please re-open if this is still an issue in the latest version.
