### ISSUE TITLE
Buried White Petal (Botania) then Bonemeal causes the following crash.

### ISSUE THREAD

**Issue by StoneLegion** [squeek502/AppleCore#50]
Not sure if there is anything else I can provide. It's 100% repeatable. It was just in dirt, placed the white petal then bonemealed it.

http://pastebin.com/3aHGxaLs

**Original Post:**
https://github.com/Vazkii/Botania/issues/1827#issuecomment-195764589

**Comment by yrsegal** [comment]
that's a dupe of #48.

**Comment by StoneLegion** [comment]
I hate you lol
