### ISSUE TITLE
Crash with forge 1808 [1.8.9]

### ISSUE THREAD

**Issue by BBoldt** [squeek502/AppleCore#52]
I think something new was added in forge regarding tooltips, seems to have broken applecore:

https://gist.github.com/1c4b0eaf697be7a973f1

**Comment by mezz** [comment]
Here's the change: https://github.com/MinecraftForge/MinecraftForge/commit/eca3b900e0301f892340c4131c45d6c723ac6126
TLDR: I made `GuiScreen.drawHoveringText` call a new public function `GuiUtils.drawHoveringText` which you'll probably want to hook into.

**Comment by squeek502** [comment]
@mezz thanks for the info.

**Comment by Xiaminou** [comment]
Any ETA on fixing this? now that pam's harvestcraft is out I'd like to use applecore and spice of life.

**Comment by squeek502** [comment]
Sorry, will try to get to it within the next few days.

**Comment by Xiaminou** [comment]
thank you, much appreciated.

**Comment by cyberpunkbln** [comment]
Hi,
sorry for my impatience but Pams Harvestcraft for 1.8.9 is out, smile:). And AppleCore is highly need for forge above 1808:).
thx

**Comment by squeek502** [comment]
Fixed by #57

**Comment by Xiaminou** [comment]
I get build failed when trying to build the latest applecore.

**Comment by GirafiStudios** [comment]
Get the latest build from the drone.io: https://drone.io/github.com/squeek502/AppleCore/files

**Comment by Xiaminou** [comment]
Thanks

**Comment by Xiaminou** [comment]
Crash with Spice of life: http://pastebin.com/P1Dcde81

Crash without spice of life inside my main modpack: http://pastebin.com/NmRf4WzM

**Comment by GirafiStudios** [comment]
Report that to Spice of Life then..

**Comment by cyberpunkbln** [comment]
thx
