### ISSUE TITLE
Where can I pick up development or deobj builds?

### ISSUE THREAD

**Issue by IceDragon200** [squeek502/AppleCore#53]
^ Title, I'd like to test against Growthcraft using a dev build

**Comment by GirafiStudios** [comment]
If you looked at the README here on github, you would see a link to the drone.io, under Building against AppleCore.
https://drone.io/github.com/squeek502/AppleCore/files

**Comment by IceDragon200** [comment]
@GirafiStudios Sorry about that, I expected to see them along with the releases.
