### ISSUE TITLE
[1.7.10] Overlapping text on debug screen

### ISSUE THREAD

**Issue by gioporta** [squeek502/AppleCore#56]
When clicking F3 to open the debug screen, AppleCore puts text in the top left that overlays default Minecraft text, making it unreadable.

Setting _show.food.stats.in.debug.overlay_ to false fixes the problem.

**Comment by squeek502** [comment]
Can I get a screenshot? Seems like some other mod is probably manually drawing the overlapping text. 
AppleCore uses the [relevant Forge event and simply adds a string to the list](https://github.com/squeek502/AppleCore/blob/1.7.10/java/squeek/applecore/client/DebugInfoHandler.java#L41).

**Comment by gioporta** [comment]
[Screenshot](http://i.imgur.com/JfqNvlk.png)

It's overlapping the first line.

**Comment by squeek502** [comment]
Very strange, but this does not seem to be an AppleCore problem. Some other mod seems to be overriding default Forge behavior and re-rendering the debug info on their own or something. Closing for now, re-open if you can reproduce this with only AppleCore + Forge.
