### ISSUE TITLE
[1.8.9] Error when trying to load using Forge 11.15.1.1855

### ISSUE THREAD

**Issue by Morpheus1101** [squeek502/AppleCore#59]
Error whilst 1st starting to load pack im making.  http://pastebin.com/dW5g0pdU

**Comment by GirafiStudios** [comment]
Can you try to narrow this down to a few mods instead of a whole pack? Because this does not happen with only Apple Core.
And do you get this crash without Apple Core in the pack?

**Comment by Morpheus1101** [comment]
Yes, with only applecore it still crashes http://pastebin.com/aGhvqrsV

**Comment by GirafiStudios** [comment]
Ohh you're not the same guy as I tried to help earlier, I thought you was. Update to the latest version from the drone.io file server here: https://drone.io/github.com/squeek502/AppleCore/files . This got fixed yesterday :)

**Comment by Morpheus1101** [comment]
Thanks :-)

**Comment by GirafiStudios** [comment]
Can you please close the issue, if this resolved your problem? :)
