### ISSUE TITLE
1.8.9 JEI reflection crash

### ISSUE THREAD

**Issue by LuxusDarkangel** [squeek502/AppleCore#60]
Apple core causing a crash with the latest version from drone.io (AppleCore-mc1.8.9-1.3.0+168.59ffb)
http://pastebin.com/Fb4q0g0H

**Comment by squeek502** [comment]
Closing this because it looks like its the JEI integration thats causing the error, and that code has changed since the AppleCore build in the crash log. Please re-open if it's still an issue.
