### ISSUE TITLE
Latest update not uploaded to mods.curse.com

### ISSUE THREAD

**Issue by JoelZBub** [squeek502/AppleCore#61]
The latest update posted 15 days ago fixing the tooltips issue has not been updated on mods.curse.com . Modpacks using the Curse launcher, and using the latest forge can't use AppleCore.

**Comment by GirafiStudios** [comment]
Get it from the drone.io build server.. https://drone.io/github.com/squeek502/AppleCore/files

**Comment by JoelZBub** [comment]
Thanks for that suggestion.
I already have, and manually updating it works just fine, but that does nothing for the less technically minded who rely on the Curse launcher for automatic updates. 
I reported it here, as I assumed a GitHub issue would be seen sooner than a complaint in the comments on the Curse site.

**Comment by squeek502** [comment]
Yeah, sorry, will get on this soon.

**Comment by squeek502** [comment]
Done: http://minecraft.curseforge.com/projects/applecore/files
