### ISSUE TITLE
Crashes everytime when trying to start up Minecraft

### ISSUE THREAD

**Issue by ToadsworthLP** [squeek502/AppleCore#62]
The 1.8.9 version crashes the game even before the game window shows up!
PS: Used latest Forge version

> [18:45:57] [main/DEBUG] [FML/]: Injecting tracing printstreams for STDOUT/STDERR.
> [18:45:57] [main/INFO] [FML/]: Forge Mod Loader version 11.15.1.1855 for Minecraft 1.8.9 loading
> [18:45:57] [main/INFO] [FML/]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Users\Manuel\Documents\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
> [18:45:57] [main/DEBUG] [FML/]: Java classpath at launch is C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\minecraftforge\forge\1.8.9-11.15.1.1855\forge-1.8.9-11.15.1.1855.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\ow2\asm\asm-all\5.0.3\asm-all-5.0.3.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\jline\jline\2.13\jline-2.13.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\java\dev\jna\jna\3.4.0\jna-3.4.0.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\sf\jopt-simple\jopt-simple\4.6\jopt-simple-4.6.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\io\netty\netty-all\4.0.23.Final\netty-all-4.0.23.Final.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\google\guava\guava\17.0\guava-17.0.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-lang3\3.3.2\commons-lang3-3.3.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\commons-io\commons-io\2.4\commons-io-2.4.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\commons-codec\commons-codec\1.9\commons-codec-1.9.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\google\code\gson\gson\2.2.4\gson-2.2.4.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\mojang\authlib\1.5.21\authlib-1.5.21.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\com\mojang\realms\1.7.59\realms-1.7.59.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-api\2.0-beta9\log4j-api-2.0-beta9.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\apache\logging\log4j\log4j-core\2.0-beta9\log4j-core-2.0-beta9.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\libraries\tv\twitch\twitch\6.5\twitch-6.5.jar;C:\Users\Manuel\Documents\Curse\Minecraft\Install\versions\forge-11.15.1.1855\forge-11.15.1.1855.jar
> [18:45:57] [main/DEBUG] [FML/]: Java library path at launch is C:\Users\Manuel\Documents\Curse\Minecraft\Install\versions\forge-11.15.1.1855\forge-11.15.1.1855-natives-710101609468944
> [18:45:57] [main/DEBUG] [FML/]: Enabling runtime deobfuscation
> [18:45:57] [main/DEBUG] [FML/]: Instantiating coremod class FMLCorePlugin
> [18:45:57] [main/DEBUG] [FML/]: Added access transformer class net.minecraftforge.fml.common.asm.transformers.AccessTransformer to enqueued access transformers
> [18:45:57] [main/DEBUG] [FML/]: Enqueued coremod FMLCorePlugin
> [18:45:57] [main/DEBUG] [FML/]: Instantiating coremod class FMLForgePlugin
> [18:45:57] [main/DEBUG] [FML/]: Enqueued coremod FMLForgePlugin
> [18:45:57] [main/DEBUG] [FML/]: All fundamental core mods are successfully located
> [18:45:57] [main/DEBUG] [FML/]: Attempting to load commandline specified mods, relative to C:\Users\Manuel\Documents\Curse\Minecraft\Instances\Continuum Pack
> [18:45:57] [main/DEBUG] [FML/]: Discovering coremods
> [18:45:57] [main/DEBUG] [FML/]: Examining for coremod candidacy AppleCore-mc1.8.9-1.3.0.jar
> [18:45:57] [main/TRACE] [FML/]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.8.9-1.3.0.jar, it will be examined later for regular @Mod instances
> [18:45:57] [main/DEBUG] [FML/]: Instantiating coremod class AppleCore
> [18:45:57] [main/DEBUG] [FML/]: The coremod squeek.applecore.AppleCore requested minecraft version 1.8.9 and minecraft is 1.8.9. It will be loaded.
> [18:45:57] [main/DEBUG] [FML/]: Enqueued coremod AppleCore
> [18:45:57] [main/DEBUG] [FML/]: Examining for coremod candidacy Baubles-1.8.9-1.1.3.0.jar
> [18:45:57] [main/DEBUG] [FML/]: Not found coremod data in Baubles-1.8.9-1.1.3.0.jar
> [18:45:57] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [18:45:57] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
> [18:45:57] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [18:45:57] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
> [18:45:57] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
> [18:45:57] [main/DEBUG] [FML/]: Injecting coremod FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin} class transformers
> [18:45:57] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.BlamingTransformer
> [18:45:57] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.SideTransformer
> [18:45:57] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriptionTransformer
> [18:45:57] [main/TRACE] [FML/]: Registering transformer net.minecraftforge.fml.common.asm.transformers.EventSubscriberTransformer
> [18:45:57] [main/DEBUG] [FML/]: Injection complete
> [18:45:57] [main/DEBUG] [FML/]: Running coremod plugin for FMLCorePlugin {net.minecraftforge.fml.relauncher.FMLCorePlugin}
> [18:45:57] [main/DEBUG] [FML/]: Running coremod plugin FMLCorePlugin
> [18:45:58] [main/DEBUG] [FML/]: Read 825 binary patches
> [18:45:58] [main/DEBUG] [FML/]: Loading deobfuscation resource /deobfuscation_data-1.8.9.lzma with 27891 records
> [18:45:59] [main/INFO] [FML/]: Found valid fingerprint for Minecraft Forge. Certificate fingerprint e3c3d50c7c986df74c645c0ac54639741c90a557
> [18:45:59] [main/INFO] [FML/]: Found valid fingerprint for Minecraft. Certificate fingerprint cd99959656f753dc28d863b46769f7f8fbaefcfc
> [18:45:59] [main/DEBUG] [FML/]: Coremod plugin class FMLCorePlugin run successfully
> [18:45:59] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
> [18:45:59] [main/DEBUG] [FML/]: Injecting coremod FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin} class transformers
> [18:45:59] [main/DEBUG] [FML/]: Injection complete
> [18:45:59] [main/DEBUG] [FML/]: Running coremod plugin for FMLForgePlugin {net.minecraftforge.classloading.FMLForgePlugin}
> [18:45:59] [main/DEBUG] [FML/]: Running coremod plugin FMLForgePlugin
> [18:45:59] [main/DEBUG] [FML/]: Coremod plugin class FMLForgePlugin run successfully
> [18:45:59] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLDeobfTweaker
> [18:45:59] [main/DEBUG] [FML/]: Loaded 165 rules from AccessTransformer config file forge_at.cfg
> [18:45:59] [main/DEBUG] [FML/]: Validating minecraft
> [18:45:59] [main/DEBUG] [FML/]: Minecraft validated, launching...
> [18:45:59] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.relauncher.CoreModManager$FMLPluginWrapper
> [18:45:59] [main/DEBUG] [FML/]: Injecting coremod AppleCore {squeek.applecore.AppleCore} class transformers
> [18:45:59] [main/TRACE] [FML/]: Registering transformer squeek.applecore.asm.TransformerModuleHandler
> [18:45:59] [main/DEBUG] [FML/]: Injection complete
> [18:45:59] [main/DEBUG] [FML/]: Running coremod plugin for AppleCore {squeek.applecore.AppleCore}
> [18:45:59] [main/DEBUG] [FML/]: Running coremod plugin AppleCore
> [18:45:59] [main/DEBUG] [FML/]: Coremod plugin class AppleCore run successfully
> [18:45:59] [main/INFO] [LaunchWrapper/]: Loading tweak class name net.minecraftforge.fml.common.launcher.TerminalTweaker
> [18:45:59] [main/INFO] [LaunchWrapper/]: Calling tweak class net.minecraftforge.fml.common.launcher.TerminalTweaker
> [18:45:59] [main/INFO] [LaunchWrapper/]: Launching wrapped minecraft {net.minecraft.client.main.Main}
> [18:46:00] [main/ERROR] [LaunchWrapper/]: Unable to launch
> java.lang.reflect.InvocationTargetException
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_25]
>     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_25]
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_25]
>     at java.lang.reflect.Method.invoke(Method.java:483) ~[?:1.8.0_25]
>     at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
>     at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/gui/GuiScreen
>     at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
>     ... 6 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.gui.GuiScreen
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
>     at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
>     ... 6 more
> Caused by: net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerException: Exception in class transformer squeek.applecore.asm.TransformerModuleHandler@907f2b7 from coremod AppleCore
>     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:234) ~[forge-1.8.9-11.15.1.1855.jar:?]
>     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
>     at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
>     ... 6 more
> Caused by: java.lang.RuntimeException: Unexpected instruction pattern encountered in drawHoveringText
>     at squeek.applecore.asm.module.ModuleDrawTooltip.addDrawHoveringTextHook(ModuleDrawTooltip.java:69) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
>     at squeek.applecore.asm.module.ModuleDrawTooltip.transform(ModuleDrawTooltip.java:33) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
>     at squeek.applecore.asm.TransformerModuleHandler.transform(TransformerModuleHandler.java:40) ~[AppleCore-mc1.8.9-1.3.0.jar:?]
>     at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:230) ~[forge-1.8.9-11.15.1.1855.jar:?]
>     at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:279) ~[launchwrapper-1.12.jar:?]
>     at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:176) ~[launchwrapper-1.12.jar:?]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_25]
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_25]
>     at net.minecraft.client.main.Main.main(SourceFile:41) ~[Main.class:?]
>     ... 6 more
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:30)
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at java.lang.SecurityManager.checkExit(SecurityManager.java:761)
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at java.lang.Runtime.exit(Runtime.java:107)
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at java.lang.System.exit(System.java:968)
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)
> [18:46:00] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1052]:   at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
> <

**Comment by GirafiStudios** [comment]
Get the latest version from the drone.io file server: https://drone.io/github.com/squeek502/AppleCore/files
Please look if your issue have been reported before, before posting an issue. This have already been reported like 5 times.

**Comment by squeek502** [comment]
I don't mind the reports. I really need to get a fixed version properly released. Will do that tonight.

**Comment by squeek502** [comment]
Should be fixed in v1.3.1: http://minecraft.curseforge.com/projects/applecore/files
