### ISSUE TITLE
[1.9.4] Health regen is incorrect

### ISSUE THREAD

**Issue by SilentChaos512** [squeek502/AppleCore#65]
I've noticed health regen behaves differently with AppleCore installed on 1.9.4. Specifically, it seems like the old style of regen, instead of what vanilla does now: rapid regen when the player has saturation. I'm guessing this is unintended?

**Comment by squeek502** [comment]
Yes, definitely unintended. Didn't realize that changed, thanks for the heads up.

**Comment by squeek502** [comment]
Should be fixed, will release a new version officially tomorrow most likely. You can test it by downloading the latest build here if you want: https://drone.io/github.com/squeek502/AppleCore/files

**Comment by squeek502** [comment]
Released: https://github.com/squeek502/AppleCore/releases/tag/v1.3.3
