### ISSUE TITLE
Request: a separate mod for non-coremod features

### ISSUE THREAD

**Issue by mezz** [squeek502/AppleCore#69]
I would like to be able to use the food value tooltip without the coremod or API parts of Applecore.

I think it should be possible once this commit makes it to the 1.10.x branch https://github.com/MinecraftForge/MinecraftForge/pull/3034.

**Comment by squeek502** [comment]
Can do. Note that it wouldn't be a purely client-side mod, though, as it'd still need to sync saturation from the server in order to display it accurately on the HUD (vanilla only syncs saturation when health or hunger changes).

**Comment by squeek502** [comment]
Working on this here: https://github.com/squeek502/AppleSkin

There's still some duplication of functionality between the two mods at the moment, so if they are installed together they will step on eachother's toes a bit. I'll probably end up splitting them into two totally separate mods (AppleCore won't add HUD stuff, AppleSkin won't depend on AppleCore).

**Comment by squeek502** [comment]
Released: https://minecraft.curseforge.com/projects/appleskin
