### ISSUE TITLE
[1.10.2] Crash rendering JEI Screen list of items caused by Applecore

### ISSUE THREAD

**Issue by Morpheus1101** [squeek502/AppleCore#70]
crash log @ http://pastebin.com/rueypGTH

**Comment by squeek502** [comment]
Thanks, looks like RenderTooltipEvent got merged into 1.10.2, will get a compatible version released soon.

**Comment by Morpheus1101** [comment]
ok, thanks :)

**Comment by MakerTim** [comment]
Will guess same error
here is my crashlog

just crashes when opening ui
http://pastebin.com/Q9Z0trxv

**Comment by squeek502** [comment]
Fixed in v1.3.6: https://github.com/squeek502/AppleCore/releases/tag/v1.3.6

**Comment by ArbitraryHubris** [comment]
many thanks for the fast turnaround, @squeek502
