### ISSUE TITLE
[1.9.4]

### ISSUE THREAD

**Issue by SoldierKucha** [squeek502/AppleCore#72]
AppleCore broke my ui 
![2016-08-14_00 54 21](https://cloud.githubusercontent.com/assets/15803655/17644731/5d5a86ea-6197-11e6-9724-02d2a1c2cec3.png)

**Comment by squeek502** [comment]
Could you give more information? I assume you're referring to the tooltip not showing up?

Can you post your client log? Do you have any other mods installed? Does it happen when only AppleCore is installed?

**Comment by squeek502** [comment]
What version of Forge are you using?

**Comment by SoldierKucha** [comment]
Yep, it happens only with applecore. I have also installed betterfps, cooking for blockheads, fastleafdecay, jurassicraft, llibrary, mantle, optifine, pam's harvestcraft, quark, realsiticitemdrops, roguelike dungeons, spiceoflife, tconstruct, vanilla-immersion, veinminer, waila. What kind of log you want?

**Comment by SoldierKucha** [comment]
And im using  12.17.0.2051 version of forge

**Comment by GirafiStudios** [comment]
That is the problem then. Use any version before that, and you should be good :)

**Comment by SoldierKucha** [comment]
k

**Comment by SoldierKucha** [comment]
Wow. I wish every tech support will be as fast as yours

**Comment by SoldierKucha** [comment]
Aaaaand... It worked! Thank you guys!

**Comment by GirafiStudios** [comment]
No problem! Glad it worked :)
