### ISSUE TITLE
[1.10.2] Ticking player

### ISSUE THREAD

**Issue by FiveEYZ** [squeek502/AppleCore#74]
Before I got this error and the server kicked me out, I was in creative mode for a long period of time before I went to survival and tried to eat.

I think thats how this error happend: https://gist.github.com/FiveEYZ/c69c359c3e806ec318b55abf3d4b6d6a

Using:
forge-1.10.2-12.18.1.2065-universal
AppleCore-mc1.10.2-2.0.0

and this modpack
https://minecraft.curseforge.com/projects/all-the-mods

**Comment by squeek502** [comment]
This is a Spice of Life bug, possibly the same issue as https://github.com/squeek502/SpiceOfLife/issues/97
