### ISSUE TITLE
Mod disables naturalRegeneration gamerule

### ISSUE THREAD

**Issue by AveryCorvus** [squeek502/AppleCore#76]
Pretty straightforward:

Without AppleCore (2.0.0 in my case, for 1.10.2), I can jump off a ledge with naturalRegeneration set to false and won't heal. I can exit that same world, add AppleCore, and my wounds will heal right up. Set the gamerule to false again just to confirm, and they still were healing.

Since Tinker's Construct no longer has the UHC section in its config file for 1.10.2, it's actually super valuable for no-regeneration servers that AppleCore not disable this gamerule.

**Comment by GirafiStudios** [comment]
Does this happen when you only have Apple Core installed?
Because Apple Core should not do anything when installed alone :)

**Comment by AveryCorvus** [comment]
Correct. Just tried again to confirm:

If I have only AppleCore installed, no other mods, food heals me even with naturalRegeneration is off.

If I close out Minecraft, delete AppleCore, and run pure vanilla Forge Minecraft on that same world, the gamerule works properly and I do not heal.

Note that I used the same save for both tests, so I definitely spelled the gamerule right since I only typed it out once (EDIT: That is, the gamerule was spelled right because when AppleCore was removed the rule took effect)

**Comment by squeek502** [comment]
Definitely possible that this is the case. Will look into it.

**Comment by squeek502** [comment]
Silly mistake. Will get a fixed version released soon.

**Comment by squeek502** [comment]
Fixed in v2.0.1 / v1.3.7: https://github.com/squeek502/AppleCore/releases/tag/v2.0.1
