### ISSUE TITLE
crash with forge 2123

### ISSUE THREAD

**Issue by Evinsta** [squeek502/AppleCore#80]
Since updating my mod pack if i try and load the pack with applecore  enabled i get
this error - http://pastebin.com/P7aVdCHD
i have tried it with the only 2 mods is applecore and spiceolife
i use applecore because of spice of life

**Comment by GirafiStudios** [comment]
What versions of Spice of Life and Apple Core are you using ? :)

**Comment by Evinsta** [comment]
AppleCore-mc1.10.2-2.0.1 and SpiceOfLife-mc1.9.4-1.3.6.jar
i need to run the latest forge so i can run sponge for the enjin website plugin

**Comment by GirafiStudios** [comment]
Does this happen if you don't use Sponge, but just Forge ? :)

**Comment by Evinsta** [comment]
yep I did a disable all mods  on the client and added them in 1 by 1 until i found the ones that crashed the client on load. then I disabled everything and put only Spice of Life and Apple Core  back in = crash.  enabled all other mods  except for Spice of Life and Apple Core  = no crash. even tried no mods enabled except for applecore only = crash.

**Comment by Evinsta** [comment]
currently i have my pack server and client running on forge 2123 with all other mods except for Spice of Life and Apple Core

**Comment by GirafiStudios** [comment]
Hmm okay. Does this happen with Forge 12.18.2.2122 then?

**Comment by squeek502** [comment]
Here's the changelog for Forge 2123:
- draco18s: Added events for crop growth (#3320)

So it looks like overlap of functionality with AppleCore. Will take a look at the Forge events and see if it makes the AppleCore events redundant.

EDIT: Relevant PR: https://github.com/MinecraftForge/MinecraftForge/pull/3320

**Comment by squeek502** [comment]
Looks like Forge's events are mostly the same as AppleCore's, except AppleCore provides growth events for  a few things that Forge doesn't (saplings being the most important I could see).

For comparison:
- https://github.com/squeek502/AppleCore/blob/1.10.2/java/squeek/applecore/api/plants/PlantGrowthEvent.java
- https://github.com/MinecraftForge/MinecraftForge/blob/HEAD/src/main/java/net/minecraftforge/event/world/BlockEvent.java#L291-L345

I don't immediately see anything that is possible with the AppleCore events that is not possible with the Forge ones, though, so it might be worth deprecating the AppleCore growth events, removing the ASM for them, and redirecting the event dispatching in the API to the Forge events.

Support for sapling growth, etc, would either need to continue being ASMed by AppleCore or PRed into Forge.

**Comment by squeek502** [comment]
Should be fixed in v2.1.0: https://github.com/squeek502/AppleCore/releases/tag/v2.1.0

**Comment by dungcoigioi** [comment]
https://pastebin.com/mUBbjB71
Help me please. Minecraft crashed and I think it's AppleCore
