### ISSUE TITLE
AppleCore doesn't trigger an error when used with the wrong MC version

### ISSUE THREAD

**Issue by Syndaryl** [squeek502/AppleCore#84]
Which is causing errors and threatening messages in the Forge log...

**Comment by GirafiStudios** [comment]
Well first of all Apple Core is not released for 1.11.2 just yet. 
And yes Apple Cores ID for 1.11.2 is lowercased https://github.com/squeek502/AppleCore/blob/1.11.2/java/squeek/applecore/ModInfo.java#L5.

**Comment by Syndaryl** [comment]
OK, I'm a little confused since I got it off Curseforge yesterday (along with Appleskin). Looking at the JAR again it's the 1.10.2 not 1.11.2 - but I have no idea why forge wouldn't just reject it for being the wrong version entirely. *shrug* Oh well, sorry for bothering you.

**Comment by squeek502** [comment]
Yeah, it might be a good idea for us to use `acceptedMinecraftVersions` to make Forge trigger an error on incompatible MC versions. Even weirder is that the core mod part of AppleCore *is* locked to the MC version and definitely wouldn't have loaded if you tried to use the 1.10.2 version with 1.11.2.

Re-opening for now, will close again when `acceptedMinecraftVersions` gets set.

**Comment by Syndaryl** [comment]
Sounds good for me.

**Comment by squeek502** [comment]
Also worth mentioning just in case you weren't aware that AppleSkin doesn't depend on AppleCore, it's completely standalone.

**Comment by Syndaryl** [comment]
I didn't realize that yesterday, but I put two and two together finally today :)

**Comment by squeek502** [comment]
@Syndaryl released an actual 1.11.2 version as well: https://minecraft.curseforge.com/projects/applecore/files/2378384

**Comment by Syndaryl** [comment]
Most excellent!
