### ISSUE TITLE
[1.7.10] Incompatible with GC Canned Food and some UsefulFoods

### ISSUE THREAD

**Issue by dillasyx** [squeek502/AppleCore#95]
Hey,

i wanted to use AppleCore, HungerOverhaul and The Spice of Life in my modpack, but some items aren't compatible as it looks like.
Galacticraft Canned Food with apples, carrots, potatoes and watermelon, aren't shown in The Spice of Life and don't show how much they feed.
Also the cakes and soups from UsefulFoods.

**Comment by squeek502** [comment]
Those mods would need to be updated to follow https://github.com/squeek502/AppleCore/wiki/Integrating-food-items-with-AppleCore
