### ISSUE TITLE
A segunda barra de fome nao aparece

### ISSUE THREAD

**Issue by Katosh13** [squeek502/AppleCore#99]
Ola estou tendo um pequeno erro de detalhe o problema e que a segunda barra de fome nao esta aparecendo.
eu estou jogando na 1.10.2 se voces corrigirem isso eu vou ficar muito feliz e continuar com esse mod no meus modpacks

**Comment by Katosh13** [comment]
por favor lance outra versão do mod

**Comment by squeek502** [comment]
Que se trasladó a AppleSkin

https://minecraft.curseforge.com/projects/appleskin
